# -*- coding: utf-8 -*-
##############################################################################
#
#    OpenERP, Open Source Management Solution
#    Copyright (C) 2004-2010 Tiny SPRL (<http://tiny.be>).
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Affero General Public License as
#    published by the Free Software Foundation, either version 3 of the
#    License, or (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU Affero General Public License for more details.
#
#    You should have received a copy of the GNU Affero General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
##############################################################################
# Generated by the Odoo plugin for Dia !
{
    'name': 'L10n_ve_dpt',
    'version': '1.0',
    'author': 'Koyobo-Ve',
    'website': '',
    'category': 'Desconocida',
    'summary': 'Desconocida',
    'description': """ Coloque la Descripción """,
    'depends': ['base'

                ],
    'data': ['security/ir.model.access.csv',
             'views/L10n_ve_dpt_view.xml',
             'data/prueba_data.xml'
             ],
    'demo': [],
    'css': ['static/src/less/L10n_ve_dpt.less'],
    'qweb': [],
    'installable': True,
    'auto_install': False,
    'application': True
}
