# -*- coding: utf-8 -*-
##############################################################################
#
#    OpenERP, Open Source Management Solution
#    Copyright (C) 2004-2010 Tiny SPRL (<http://tiny.be>).
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Affero General Public License as
#    published by the Free Software Foundation, either version 3 of the
#    License, or (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU Affero General Public License for more details.
#
#    You should have received a copy of the GNU Affero General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
##############################################################################
# Generated by the Odoo plugin for Dia !
from odoo import api, fields, models


class regiones(models.Model):
    _name = 'regiones'
    # _rec_name = ''
    # _order = ''
    _description = 'Regiones de la Republica Bolivariana de Venezuela'


    nombre_reg = fields.Char(string='Nombre')
    estado_ids = fields.One2many('estados' , 'region_id', string='Estados')


class estados(models.Model):
    _name = 'estados'
    # _rec_name = ''
    # _order = ''
    _description = 'Estados de la Republica Bolivariana de Venezuela'


    region_id = fields.Many2one('regiones', string='Region', required=True )
    nombre_est = fields.Char(string='Nombre del Estado',  required=True)
    municipios_ids = fields.One2many('municipios', 'estado_id', string='Municipios',  required=True)


class municipios(models.Model):
    _name = 'municipios'
    # _rec_name = ''
    # _order = ''
    _description = 'Municipios de la Republica Bolivariana de Venezuela'


    estado_id = fields.Many2one('estados', string='Estado',  required=True)
    nombre_mun = fields.Char(string='Nombre del Municipio',  required=True)
    parroquias_ids = fields.One2many('parroquias', 'municipio_id', string='Parroquias',  required=True,)


class parroquias(models.Model):
    _name = 'parroquias'
    # _rec_name = ''
    # _order = ''
    _description = 'Parroquias de la Republica Bolivariana de Venezuela'


    municipio_id = fields.Many2one('municipios',  string='Municipios',  required=True)
    nombre_parroquia = fields.Char(string='Nombre de la Parroquia',  required=True)
    localidad_ids = fields.One2many('localidades', 'parroquia_id', string='Localidades',  required=True)


class localidades(models.Model):
    _name = 'localidades'
    # _rec_name = ''
    # _order = ''
    _description = 'Localidades de la Republica Bolivariana de Venezuela'


    parroquia_id = fields.Many2one('parroquias', string='Parroquias',  required=True)
    nombre_localidad = fields.Char(string='Nombre de la Localidad',  required=True, help='Urbanizacion, Barrio, Caserio, etc.')


class direccion(models.Model):
    _name = 'direccion'
    # _rec_name = ''
    # _order = ''
    _description = 'Direccion Especifica del Personal'


    calle = fields.Char(string='Calle o Avenida',  required=True)
    vereda = fields.Char(string='Vereda o Piso',  required=True)
    casa = fields.Char(string='Munero de Casa o Apartamento',  required=True)


